### ISSUE TITLE
[FeatureSuggestion] Play sound on intro

### ISSUE THREAD

**Issue by Doresain** [WBHarry/introduce-me#11]
So, I will prefix this with: 
1) Killer module man, very stylish, great idea, thank you!
2) I will understand if you have no interest in mucking with the sound APIs, I don't either! :)

That said, it would be cool if, when the intro is triggered, a sound effect was also played. This introduces a bunch of potential complexity though:

- You'd need options both for a default introduction sound as a fallback and for specifying a sound per-actor. Probably also a 'turn sounds off entirely' toggle?

- Ideally the sound duration and the intro banner duration line up so the sound isn't playing after the banner fades, which either means truncating whatever sound is played and fading it out when the banner fades OR allowing the user to configure the duration of the banner... or both?

- I don't even know if this is possible, I couldn't tell from the API docs, but allowing the user to specify a start time in seconds for a sound would be the fanciest.

**Comment by WBHarry** [comment]
I just released version 0.9.4. You can now add audio to dispositions, templates and individual actors. Simple sounds, themseongs or what-have-you. 🥳 
https://github.com/WBHarry/introduce-me/releases/tag/0.9.4
