### ISSUE TITLE
Token display name changes

### ISSUE THREAD

**Issue by WyntherKnight** [WBHarry/introduce-me#17]
When a player token uses this module, it automatically sets the "Display Name" to "Hovered By Anyone". even in the prototype setting of the Actor Sheet in the Actors Directory. It doesn't matter what you set the Display Name to.

**Comment by WBHarry** [comment]
That's an original, intended feature. My reasoning is that if you have introduced someone, then they are known to the players. From my own DM:ing, I think it can be helpful for the players to be able to hover such a character to remember the name, and even to see the spelling.

Perhaps this should be an optional thing in the Module Settings if it's unwanted?

**Comment by WyntherKnight** [comment]
Yeah, make it optional. Some DMs and or players may not want it that way.

**Comment by WBHarry** [comment]
Fair enough! I released version 0.9.4.1 that introduces this module setting. The feature is now off by default 😄
