### ISSUE TITLE
Mute Sound Error 

### ISSUE THREAD

**Issue by 2old-4this** [WBHarry/introduce-me#18]
If there is no sound enabled or muted then I'm getting this error. 

![image](https://user-images.githubusercontent.com/71936702/174644890-76b7609f-b644-4409-80b3-c7ce3455bf5c.png)

if i pick a sound it's working perfectly

**Comment by WBHarry** [comment]
Good catch. I was a bit too quick in the minor version I released last night.

I released version 0.9.4.2 just now that fixes it. A single `?` was missing in the code 😁
