### ISSUE TITLE
V8 Compatibility 

### ISSUE THREAD

**Issue by WallaceMcGregor** [WBHarry/introduce-me#19]
Although in the module.json it says that the minimum version is 8, it does not work. I am in version 0.8.9 and I have not been able to install it. Maybe it is because before versions were 0.8.X instead of 8.

**Comment by WBHarry** [comment]
Heya. Good catch. That was indeed the issue 😁 
I released a new minor version, 0.9.4.3 that set the minimumCoreVersion correctly. I tested it on 0.8.9 and was able to download and use it.

**Comment by WallaceMcGregor** [comment]
Thanks! I can now install it.👌

The only thing that does not work is the template menu. Pressing the button does not open it.

**Comment by WBHarry** [comment]
Interesting, I did set up and use a template when I tried it on 0.8.9. 
Could you open up the console in foundry (F12), and check in the 'Console' tab if there's any informative error popping up when you try to open the template menu? 🤔

**Comment by WBHarry** [comment]
Hm, I understand the error, but not how it could happen. I tried on 0.8.9, OSE system with templates just now 😅  

If you'd be willing to give me a little more debugging info, it'd be neat if you could try checking something in the console. If you type and enter: **Handlebars.helpers**, you'll get a list you can look in. I'm interested in what's in that list.

The error is essentially saying that a helper method supplied by Foundry itself doesn't exist, which is strange.

**Comment by WallaceMcGregor** [comment]
I don't know if this is it.

![chrome_dgb0LetXiK](https://user-images.githubusercontent.com/17795541/174876483-b8b3bc13-036c-449c-b5ef-de9e606e7c33.jpg)

**Comment by WallaceMcGregor** [comment]
The template menu is now working!

Thanks.
