### ISSUE TITLE
[FeatureSuggestion] Attributes in Flavor Text

### ISSUE THREAD

**Issue by abctuba** [WBHarry/introduce-me#2]
A nice addition would be to be able to reference character data in the flavor text.  For example race, class, etc... Something like [[@details.race]]

**Comment by WBHarry** [comment]
That could be done, but I'm curious about the usecase.
As of the moment, you have to set the flavor text for each individual Actor. My thinking is that the character data may just aswell be written out in plaintext at that point. IE: Lord Flaillington The Wild Elf with a flavor text of: 'The wildest elf there was' wouldn't gain much by being 'The wildest [[@details.race]] there was'.

For what sort of situation do you want this? 😃

**Comment by abctuba** [comment]
Just thinking of saving keystrokes.  I could copy/pasta a whole bunch of
characters with information already available in the world.  Yeah not a big
difference, but if you are ever under the hood it would be nice.

**Comment by WBHarry** [comment]
I added this feature in version 0.9.2.3. The formatting is setup by foundry standard, ex: @details.type.value.

Hope it'll be useful! 😁 
I think it'll become more useful together with upcoming module features.

**Comment by abctuba** [comment]
Awesome, thanks!
