### ISSUE TITLE
Introduce with Permission doesn't work

### ISSUE THREAD

**Issue by Txus5012** [WBHarry/introduce-me#23]
Hi. It seems that the option to give limited permission to players after introduction doesn't work anymore. The permissions don't change.
I tried it in different systems.

**Comment by WBHarry** [comment]
Hm, I can't replicate the issue on Foundry V9.
I did correct an error that made the permission change only apply to the actual token on the screen though - IE at the moment if you drag out a new token from the actor, that one won't have the limited permission set. I'll push this out together with V10 things I'm looking at currently.

Is the above the issue you were having? Looking at the permissions for the actor will currently show it not changing :grin:

**Comment by Txus5012** [comment]
Maybe I didn't understand what this feature is for.

I thought that this option changed the permission of the actor, so it showed to the players in the actor's tab because "he/she already introduced himself/herself".
![Permission](https://user-images.githubusercontent.com/87753744/179175410-e9d472e5-286f-4b56-bbc0-21779da24d3b.jpg)
This is what I wrote it didn't update (tried with the last update too).

**Comment by Txus5012** [comment]
I've been testing this more. It seems to work only if "Set Display Name" is also activated (I had it desactivated because I always set the Display Name to "Hovered by Anyone").

**Comment by Txus5012** [comment]
That seems to work. Thanks for the quick fix!
