### ISSUE TITLE
[FeatureSuggestion] select color by token disposition

### ISSUE THREAD

**Issue by rinnocenti** [WBHarry/introduce-me#4]
it would be interesting to configure a default color in the settings for each token disposition (hostile, neutral friendly)

**Comment by WBHarry** [comment]
Unless I'm missunderstanding you, that's available now in 9.0.1. The 'Color Settings' menu in the module's settings allows you to set the Background Color and the Text Color for each token disposition (and players seperately).

**Comment by rinnocenti** [comment]
if it does is not very clear.
see how it appears, it has no indication of which is which

![image](https://user-images.githubusercontent.com/3178127/173220066-d094e73a-4555-459f-b8c8-92d9fdbdfdd3.png)

**Comment by rinnocenti** [comment]
seems to be some race condition, I tried the "find the culprit" it is accusing the token Magic FX, but if I deactivate it, it still doesn't solve.

**Comment by WBHarry** [comment]
How interesting. The implementation only worked on the Node version of Foundry, and not on Electron. This is how it always looked for me in the Node version on chrome 😆 
![image](https://user-images.githubusercontent.com/89362246/173222436-5d383419-f701-43eb-935a-7c998c45f425.png)
I released version 0.9.1.1 with a fix for it.
