### ISSUE TITLE
[FeatureSuggestion] being able to choose the colors configured in the settings panel

### ISSUE THREAD

**Issue by rinnocenti** [WBHarry/introduce-me#5]
by the looks of it, in settings you can only test the colors of the banners, but it would be interesting to be able to define them as some id and to be able to select the configuration there in the HUD token.
Or at least have a function in the API to do it

**Comment by WBHarry** [comment]
The idea would be to essentially save color setups that could then be selected? That could be interesting. 
I'm imagining creating a 'Villain' tag and then selecting it in a dropdown from the HUD.

**Comment by WBHarry** [comment]
I just released version 0.9.2 with this feature 😁
