### ISSUE TITLE
[Feature Request] Hotkeyable

### ISSUE THREAD

**Issue by cadowtin** [WBHarry/introduce-me#7]
Add the ability to show it on a hotkey

**Comment by WBHarry** [comment]
Heya! This is already available through included macros.
![image](https://user-images.githubusercontent.com/89362246/173223056-f427942a-246c-4271-a562-6113f73375b2.png)
Just drag the macros out to your macro bar and you'll be able to select a token and just press 1,2 or whatever your prefered setup. I quite like it that way myself. 😁 
![image](https://user-images.githubusercontent.com/89362246/173223108-e252d7e8-fdf5-449d-99fa-38617d511eac.png)
