### ISSUE TITLE
Adaptative text size ?

### ISSUE THREAD

**Issue by Steelskinz** [WBHarry/introduce-me#8]
![image](https://user-images.githubusercontent.com/93941729/173250028-c6ae6a0f-c693-494a-89f3-daced0fe61ad.png)
As you can see long names are ruining it, I do like that module a lot tho ! Good work !

**Comment by WBHarry** [comment]
Yes, this issue is a small headache of mine, haha. 😅 
I definately plan on revisiting this to improve on how it handles long texts.

**Comment by WBHarry** [comment]
I didn't actually conciously adress this issue. But as of version 0.9.3.1 (I think, it's definately there in 0.9.4 at least), this has been fixed! The banner will dynamically expand:

When the text isn't too long the image will lay overtop of the banner
![image](https://user-images.githubusercontent.com/89362246/174455395-234d3c57-f522-4e9c-bacb-4899e28fa92c.png)

When the text gets longer, the image will slide further inside as the banner gets larger, which I think is perfectly reasonable 😄 
![image](https://user-images.githubusercontent.com/89362246/174455434-b24aedae-8e8a-45fa-9e01-547c91289a21.png)
-->
![image](https://user-images.githubusercontent.com/89362246/174455442-37de100f-508e-48b7-8278-e7964fc7744c.png)

**Comment by Steelskinz** [comment]
Haha nice ! Thanks you champ ! Hope to see more module from your master brain !
