### ISSUE TITLE
[Feature Suggestion] Actor name and permission configuration

### ISSUE THREAD

**Issue by emdant** [WBHarry/introduce-me#9]
Hello, I'd like to suggest some features, the first one is to have an option to show the actor's name, not the token's name (which can be modified by modules like Token Mold).

The second suggestion is to have an option to automatically set the actors' permission to all players once the actor has been introduced. My suggestion would be to set it to "Limited" so that players can see the picture and name, but not the sheet.

**Comment by WBHarry** [comment]
That can definately be done. Good suggestions. 😄 
I'll see about getting it out in a coming version.
